my:
    greeting:  Hello,Get response after batch script run configuration from config server for spring-cloud-config-client-localgit microservice 123
    #list:
    #    values: One, Two, Three, Four, Five, Six

dev-ops:
#Common Config
  common:
  
#Web
  web:
    inbound:
      enabled: false
      curr-value: 11