my:
    greeting: Hello,Get configuration from config server for spring-cloud-config-client-localgit microservice
    list:
        values: One, Two, Three, Four, Five, Six

dev-ops:
#Common Config
  common:
  
#Web
  web:
    inbound:
      enabled: false
      curr-value: 11